---

- name: Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home

- name: Add Elasticsearch GPG key.
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  become: true

- name: Add logstash yum repo
  template:
    src: "{{ role_path }}/templates/logstash.repo.j2"
    dest: /etc/yum.repos.d/logstash.repo
  become: true

- name: Install our logstash
  yum:
    name: logstash
    state: present
  become: true
  notify: restart logstash

- name: Add our templates
  template:
    src: "{{ role_path }}/templates/{{ logstash_output_template }}"
    dest: /etc/logstash/conf.d/50_logstash-output.conf
  become: true
  notify: restart logstash

- name: Create our config
  template:
    src: "{{ role_path }}/templates/logstash-{{ base_version }}/logstash.yml.j2"
    dest: "/etc/logstash/logstash.yml"
  vars:
    - logstash_node_name: "{{ [ansible_env.HMPPS_FQDN|default('unknown'), ansible_env.HMPPS_DOMAIN|default('')]|join('.') }}"
    - logstash_pipeline_name: "main"
  become: true
  notify: restart logstash

- name: start the service
  service:
    name: logstash
    state: "{{ logstash_service_state }}"
    enabled: "{{ logstash_service_enabled }}"
  become: true

- name: Make sure logstash is running before proceeding
  wait_for:
    host: "{{ logstash_network_host }}"
    port: "{{ logstash_http_port }}"
    delay: 3
    timeout: 300
