---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    login_cmd_template: "ssh instance -F ${PWD}/molecule/ssh/config"
    ansible_connection_options:
      ansible_connection: ssh
      ansible_ssh_common_args: "-F ${PWD}/molecule/ssh/config"
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
verifier:
  name: ansible
